version: "2"

services:
  consul:
    container_name: consul
    expose:
    - "8300"
    - "8400"
    - "8500"
    - "8600"
    ports:
    - "8500:8500"
    env_file:
    - consul/localdev.env

  vault:
    container_name: vault
    expose:
    - "8125"
    - "8200"
    ports:
    - "8125:8125"
    - "8200:8200"
    links:
    - consul
    env_file:
    - vault/localdev.env

  vault-ui:
    container_name: vault-ui
    ports:
    - "8080:80"
    - "8181:443"
    volumes:
    - ../vault-ui/release:/usr/share/nginx/html
    - ./vault-ui/nginx.dev.conf:/etc/nginx/nginx.conf:ro
